---
species_file : "species/species.txt"

names:
  subset: all
  type: orto1to1

results:
  supertree: True
  consensus: True

save_proteomes:
  to_remove: []

clustering:
  c: 0.5

selecting_clusters:
  min_cluster_size: 30
  max_cluster_size: 30
  max_repeat: 0.5
  orthological: True
  choose_random: False
  excluded_species: []

bootstrap: True
bootstrap_thresh: 50

get_consensus:
  p: 0.5